services:
  - type: web
    name: taskpoint
    env: ruby
    runtime: ruby-3.3.2
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskpoint-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: GMAIL_EMAIL
        sync: false
      - key: GMAIL_PASSWORD
        sync: false

databases:
  - name: taskpoint-db
    databaseName: taskpoint_production
    user: taskpoint
