
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME_DEV"] || "to_do_list_v360_development" %>

test:
  <<: *default
  database: <%= ENV["DATABASE_NAME_TEST"] || "to_do_list_v360_test" %>

production:
  primary: &primary_production
    <<: *default
    url : <%= ENV["DATABASE_URL"] %>
    database: <%= ENV["DATABASE_NAME_PROD"] || "to_do_list_v360_production" %>

  cache:
    <<: *primary_production
    database: <%= ENV["DATABASE_NAME_PROD_CACHE"] || "to_do_list_v360_production_cache" %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: <%= ENV["DATABASE_NAME_PROD_QUEUE"] || "to_do_list_v360_production_queue" %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: <%= ENV["DATABASE_NAME_PROD_CABLE"] || "to_do_list_v360_production_cable" %>
    migrations_paths: db/cable_migrate
